CREATE PROFILE cliente_users_profile LIMIT
   FAILED_LOGIN_ATTEMPTS 10
   PASSWORD_LIFE_TIME 60
   PASSWORD_REUSE_TIME 60
   PASSWORD_REUSE_MAX 5
   PASSWORD_GRACE_TIME 10;


CREATE PROFILE cliente_users_profile LIMIT
   FAILED_LOGIN_ATTEMPTS 10
   PASSWORD_LIFE_TIME 90
   PASSWORD_REUSE_TIME 180
   PASSWORD_REUSE_MAX 3
   PASSWORD_GRACE_TIME 10
   PASSWORD_LOCK_TIME 1/24/60
   INACTIVE_ACCOUNT_TIME 365
   PASSWORD_ROLLOVER_TIME  0
   PASSWORD_VERIFY_FUNCTION ora12c_verify_function;
